### PR TITLE
Update from dotnet 2.1 to 6.0

### PR DESCRIPTION
**Pull request by jasonleenaylor**
+semver:major

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/overcrowdin/48)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
@ArmorBearer If this will cause a problem for other consumers I need to know so I can delay merging. I'm only doing this upgrade as a stop-gap, I plan to move toward a github action approach to working with Crowdin in the future.

**Comment by ArmorBearer** [comment]
@jasonleenaylor, I see that there were no code changes necessary, which is good.  But I see that the build failed.  So that will need to be resolved.

Paratext uses .NET 4.8, so we won't be able to upgrade to a version of overcrowdin which uses 6.0...

**Comment by FarmerPickles** [comment]
Thanks for the review, yes it built on my machine but the CI build has a
different setup, so I have to sort that out.
Also, the version that overcrowdin uses should be independent of what
Paratext uses. The current one is using dotnet 2.1. The only thing that
changes is the requirement of what dotnet sdks are installed on the machine
that runs overcrowdin.

**Comment by jasonleenaylor** [comment]
Superceded by move to Crowdin api v2 and dotnet 8

**Pull request closed without merging**
